# Generated by Django 3.2.4 on 2021-06-05 21:03

from django.db import migrations, models
import django.db.models.deletion
import tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('login', models.CharField(default=tracker.models.Employee.create_login, max_length=28)),
                ('email', models.EmailField(default=tracker.models.Employee.create_email, max_length=254)),
                ('birth_date', models.DateField()),
                ('address_street', models.CharField(max_length=128)),
                ('address_city', models.CharField(max_length=64)),
                ('address_postal', models.CharField(max_length=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('building_id', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Apprentice'), (2, 'Intern'), (3, 'Associate'), (4, 'Specialist'), (5, 'Team Leader'), (6, 'Manager'), (7, 'Director')])),
                ('annual_salary', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveOfAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('MAT', 'Maternity Leave'), ('PAT', 'Paternity Leave'), ('SCK', 'Sick Leave'), ('UNP', 'Unpaid Leave'), ('UEX', 'Unexcused')], max_length=28)),
                ('leave_start', models.DateField()),
                ('leave_end', models.DateField(default=None)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(default=None)),
                ('contract_type', models.CharField(choices=[('UNL', 'Unlimited'), ('LTD', 'Limited'), ('INT', 'Internship'), ('APR', 'Apprenticeship')], max_length=28)),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.location')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.position')),
            ],
        ),
    ]
