# Generated by Django 3.2.4 on 2021-06-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20210606_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='termination_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='hire_date',
            new_name='start_date',
        ),
    ]
