# Generated by Django 3.2.4 on 2021-06-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210608_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='annual_salary',
        ),
        migrations.AddField(
            model_name='contract',
            name='annual_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='job_title',
            field=models.CharField(default='some', max_length=64),
            preserve_default=False,
        ),
    ]
