# Generated by Django 3.2.4 on 2021-06-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
